name: Hello World Workflow

on:
  push:
    branches:
      - main
    workflow_dispatch: # can trigger from GUI
     
jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash
        
  goodbye:
    runs-on: self-hosted
    steps:
      - name: goodbye world
        run: echo "goodbye world"
        shell: bash
